const ListaMusicas = [
    { nome: "Elysium", artista: "Alexander Nakarada", url: "https://www.free-stock-music.com/music/alexander-nakarada-elysium.mp3" },
    { nome: "Patterns In The Sky", artista: "Vlad Gluschenko", url: "https://www.free-stock-music.com/music/vlad-gluschenko-patterns-in-the-sky.mp3" },
    { nome: "Kindness", artista: "Vlad Gluschenko", url: "https://www.free-stock-music.com/music/vlad-gluschenko-kindness.mp3" },
    { nome: "Music To Wear Fingerless Gloves To", artista: "Punch Deck", url: "https://www.free-stock-music.com/music/punch-deck-music-to-wear-fingerless-gloves-to.mp3" },
    { nome: "Tragedy", artista: "MaxKoMusic", url: "https://www.free-stock-music.com/music/maxkomusic-tragedy.mp3" },
    { nome: "TEMPEST", artista: "Audionautix", url: "https://www.free-stock-music.com/music/audionautix-tempest.mp3" },
    { nome: "GET AWAY", artista: "tubebackr", url: "https://www.free-stock-music.com/music/tubebackr-get-away.mp3" },
    { nome: "Lipsia", artista: "Sapajou", url: "https://www.free-stock-music.com/music/sapajou-lipsia.mp3" },
    { nome: "Worry Less", artista: "Sapajou", url: "https://www.free-stock-music.com/music/sapajou-worry-less.mp3" },
    { nome: "Cuba", artista: "ASHUTOSH", url: "https://www.free-stock-music.com/music/ashutosh-cuba.mp3" },
    { nome: "Rainy Days", artista: "Scandinavianz", url: "https://www.free-stock-music.com/music/scandinavianz-rainy-days.mp3" },
    { nome: "One Wish", artista: "Roa Music", url: "https://www.free-stock-music.com/music/roa-music-one-wish.mp3" },
    { nome: "Ukulele", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-ukulele.mp3" },
    { nome: "Criative Minds", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-creativeminds.mp3" },
    { nome: "A New Beginning", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-anewbeginning.mp3" },
    { nome: "Little idea", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-littleidea.mp3" },
    { nome: "Jazzy Frenchy", artista: "Benjamin Tissot", url: "https://www.bensound.com/bensound-music/bensound-jazzyfrenchy.mp3" },
    { nome: "Happy Rock", artista: "Benjamin Tissot", url: "https://www.bensound.com/bensound-music/bensound-happyrock.mp3" },
    { nome: "Hey", artista: "Benjamin Tissot", url: "https://www.bensound.com/bensound-music/bensound-hey.mp3" },
    { nome: "Cute", artista: "Benjamin Tissot", url: "https://www.bensound.com/bensound-music/bensound-cute.mp3" },
    { nome: "Memories", artista: "Benjamin Tissot", url: "https://www.bensound.com/bensound-music/bensound-memories.mp3" },
    { nome: "Going Higher", artista: "Benjamin Tissot", url: "https://www.bensound.com/bensound-music/bensound-goinghigher.mp3" },
    { nome: "Breeze", artista: "Benjamin Tissot", url: "https://www.bensound.com/bensound-music/bensound-acousticbreeze.mp3" },
    { nome: "Buddy", artista: "Benjamin Tissot", url: "https://www.bensound.com/bensound-music/bensound-buddy.mp3" },
    { nome: "Dubstep", artista: "Benjamin Tissot", url: "https://www.bensound.com/bensound-music/bensound-dubstep.mp3" },
    { nome: "Betterdays", artista: "Benjamin Tissot", url: "https://www.bensound.com/bensound-music/bensound-betterdays.mp3" },
    { nome: "Sunny", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-sunny.mp3" },
    { nome: "Energy", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-energy.mp3" },
    { nome: "Epic", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-epic.mp3" },
    { nome: "Funny Song", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-funnysong.mp3" },
    { nome: "Once Again", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-onceagain.mp3" },
    { nome: "Tomorrow", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-tomorrow.mp3" },
    { nome: "Slowmotion", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-slowmotion.mp3" },
    { nome: "Clear Day", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-clearday.mp3" },
    { nome: "Moose", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-moose.mp3" },
    { nome: "Adventure", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-adventure.mp3" },
    { nome: "The Lounge", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-thelounge.mp3" },
    { nome: "Sweet", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-sweet.mp3" },
    { nome: "Evolution", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-evolution.mp3" },
    { nome: "Inspire", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-inspire.mp3" },
    { nome: "Retro Soul", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-retrosoul.mp3" },
    { nome: "Endless Motion", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-endlessmotion.mp3" },
    { nome: "Love", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-love.mp3" },
    { nome: "Straight", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-straight.mp3" },
    { nome: "Perception", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-perception.mp3" },
    { nome: "The Jazz Piano", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-thejazzpiano.mp3" },
    { nome: "Jazz Comedy", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-jazzcomedy.mp3" },
    { nome: "Piano Moment", artista: "Bensound", url: "https://www.bensound.com/bensound-music/bensound-pianomoment.mp3" },
    { nome: "Stay Positive", artista: "FSM Team", url: "https://www.free-stock-music.com/music/fsm-team-stay-positive.mp3" },
    { nome: "Kinects", artista: "FSM Team feat. <escp>", url: "https://www.free-stock-music.com/music/fsm-team-escp-kinetics.mp3" },
    { nome: "A New Beginning", artista: "Mixaund", url: "https://www.free-stock-music.com/music/mixaund-a-new-beginning.mp3" },
    { nome: "Silent Wood", artista: " Purrple Cat", url: "https://www.free-stock-music.com/music/purrple-cat-silent-wood.mp3" },
    { nome: "Lock And Load", artista: "Hayden Folker", url: "https://www.free-stock-music.com/music/hayden-folker-lock-and-load.mp3" },
    { nome: "Electronic Dance Music | PRAY", artista: "Alex-Productions", url: "https://www.free-stock-music.com/music/alex-productions-electronic-dance-music-pray.mp3" },
    { nome: "Timeout", artista: "Scandinavianz", url: "https://www.free-stock-music.com/music/scandinavianz-timeout.mp3" },
    { nome: "Seashells", artista: "Purrple Cat", url: "https://www.free-stock-music.com/music/purrple-cat-seashells.mp3" },
    { nome: "Alive", artista: "Punch Deck", url: "https://www.free-stock-music.com/music/punch-deck-alive.mp3" },
    { nome: "Storm Of Vengeance | Orchestral Music", artista: "Solas", url: "https://www.free-stock-music.com/music/solas-storm-of-vengeance-orchestral-music.mp3" },
    { nome: "Motivate Me", artista: "Mixaund", url: "https://www.free-stock-music.com/music/mixaund-motivate-me.mp3" },
    { nome: "Upbeat", artista: "FSM Team", url: "https://www.free-stock-music.com/music/fsm-team-upbeat.mp3" },
    { nome: "Shine", artista: "LiQWYD", url: "https://www.free-stock-music.com/music/liqwyd-shine.mp3" },
    { nome: "Wanna Go", artista: "INOSSI", url: "https://www.free-stock-music.com/music/inossi-wanna-go.mp3" },
    { nome: "FUJI", artista: "tubebackr", url: "https://www.free-stock-music.com/music/tubebackr-fuji.mp3" },
    { nome: "Wonder", artista: "INOSSI", url: "https://www.free-stock-music.com/music/inossi-wonder.mp3" },
    { nome: "Aurora", artista: "Scott Buckley", url: "https://www.free-stock-music.com/music/scott-buckley-aurora.mp3" },
    { nome: "Worthy Rivals", artista: "Arthur Vyncke", url: "https://www.free-stock-music.com/music/arthur-vyncke-worthy-rivals.mp3" },
    { nome: "Sunrise In Your Eyes", artista: "Scandinavianz", url: "https://www.free-stock-music.com/music/scandinavianz-sunrise-in-your-eyes.mp3" },
]

export default ListaMusicas;